apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: poc-backstage-api
  description: The todos API
  tags:
    - todos
    - node-js-api
  links:
    - url: https://github.com/ahemadpirzada-cloud/Node.js-Api-2
      title: GitHub Repo
      icon: github
    - url: https://github.com/ahemadpirzada-cloud/Node.js-Api-2/blob/main/swagger.yaml
      title: API Spec
      icon: code
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: experimental
  owner: ahemadpirzada
  definition: |
    openapi: 3.0.1
    info:
      title: WebAPI
      version: '1.0'
    servers:
      - url: http://localhost:3080
    basePath: /api
    paths:
      /api/todos:
        get:
          tags:
            - todos
          responses:
            '200':
              description: Success
        post:
          tags:
            - todos
          requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Todos'
              text/json:
                schema:
                  $ref: '#/components/schemas/Todos'
              application/*+json:
                schema:
                  $ref: '#/components/schemas/Todos'
          responses:
            '200':
              description: Success
        put:
          tags:
            - todos
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: integer
                format: int32
          requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Todos'
              text/json:
                schema:
                  $ref: '#/components/schemas/Todos'
              application/*+json:
                schema:
                  $ref: '#/components/schemas/Todos'
          responses:
            '200':
              description: Success
        delete:
          tags:
            - todos
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: integer
                format: int32
          responses:
            '200':
              description: Success
    components:
      schemas:
        Todos:
          type: object
          properties:
            id:
              type: integer
              format: int32
            task:
              type: string
              nullable: true
            assignee:
              type: string
              nullable: true
            status:
              type: string
              nullable: true
          additionalProperties: false
